import { useEffect, useState } from "react";
import GoogleLoginButton from "../../components/GoogleLoginButton";
import WalletExpense from "@/components/WalletExpense";

export default function Home() {
  const [email, setEmail] = useState<string>("");
  const [passcode, setPasscode] = useState<string>("");
  const [showPasscodeInput, setShowPasscodeInput] = useState<boolean>(false);
  const [savedPasscode, setSavedPasscode] = useState<string>("");

  const handleLogin = (email: string) => {
    setEmail(email);
    localStorage.setItem("email", email);
  };

  useEffect(() => {
    const savedEmail = localStorage.getItem("email");
    if (savedEmail) {
      setEmail(savedEmail);
    }

    const storedPasscode = localStorage.getItem("passcode");
    if (storedPasscode) {
      setSavedPasscode(storedPasscode);
    }
  }, []);

  const handleLogout = () => {
    setEmail("");
    setPasscode("");
    setSavedPasscode("");
    localStorage.removeItem("email");
    localStorage.removeItem("passcode");
  };

  const handleSetPasscode = (event: React.ChangeEvent<HTMLInputElement>) => {
    const newPasscode = event.target.value;
    setPasscode(newPasscode);
  };

  const savePasscode = () => {
    localStorage.setItem("passcode", passcode);
    setSavedPasscode(passcode);
    setShowPasscodeInput(false);
  };

  return (
    <div className="bg-gray-100 flex flex-col items-center justify-center py-6 mt-12">
      <div className="bg-white rounded-lg p-6 max-w-sm w-full">
        {email ? (
          <>
            <div className="flex items-center h-10 mb-4">
              <div className="left flex-grow">
                <div className="text-2xl">{`${email.slice(
                  0,
                  5
                )}...${email.slice(-8)}`}</div>
              </div>
              <div className="right">
                <button
                  onClick={handleLogout}
                  className="bg-gray-100 px-4 py-2 rounded-full"
                >
                  Sign out
                </button>
              </div>
            </div>
            {savedPasscode && (
              <WalletExpense email={email} passcode={savedPasscode} />
            )}

            <div className="mt-6 text-center">
              {showPasscodeInput ? (
                <div className="border-t bg-gray-100 p-4">
                  <label>Enter your passcode</label>
                  <div>
                    <input
                      type="password"
                      name="passcode"
                      value={passcode}
                      onChange={handleSetPasscode}
                      className="p-2 border rounded"
                    />
                  </div>
                  <div>
                    <button
                      onClick={savePasscode}
                      className="bg-orange-300 px-4 py-2 rounded-full mt-2"
                    >
                      Access
                    </button>
                  </div>
                  <div className="text-sm mt-4">
                    Wallet generated by combining email address and custom
                    passcode
                  </div>
                </div>
              ) : (
                <div
                  className="mx-auto w-fit px-4 bg-gray-100 rounded-full border cursor-pointer"
                  onClick={() => {
                    setShowPasscodeInput(true);
                  }}
                >
                  {`Access ${passcode ? "Order" : ""} Wallet`}
                </div>
              )}
            </div>
          </>
        ) : (
          <div className="text-center mb-4">
            <div className="text-4xl">Suica Wallet</div>
            <div className="h-10"></div>
            <div className="text-left">
              <GoogleLoginButton onLogin={handleLogin} />
              <div className="mt-4">
                <span>
                  Please login your gmail account to access the wallet
                </span>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
